### ISSUE TITLE
shaman error in totems code

### ISSUE THREAD

**Issue by Noesis-Boss** [Kkthnx-Wow/KkthnxUI_Classic#1]
Message: ...ce\AddOns\KkthnxUI\Libraries\oUF\elements\totems.lua:93: attempt to call upvalue 'GetTotemInfo' (a nil value)
Time: Tue Feb  4 15:02:55 2020
Count: 1
Stack: ...ce\AddOns\KkthnxUI\Libraries\oUF\elements\totems.lua:93: attempt to call upvalue 'GetTotemInfo' (a nil value)
...ce\AddOns\KkthnxUI\Libraries\oUF\elements\totems.lua:93: in function <...ce\AddOns\KkthnxUI\Libraries\oUF\elements\totems.lua:79>
(tail call): ?
...ce\AddOns\KkthnxUI\Libraries\oUF\elements\totems.lua:133: in function `func'
Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:207: in function <Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:190>
(tail call): ?

Locals: self = oUF_Player {
 ReadyCheckIndicator = <unnamed> {
 }
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\portrait.lua:87
 Highlight = <unnamed> {
 }
 __tags = <table> {
 }
 CombatFade = false
 ResurrectIndicator = <unnamed> {
 }
 DebuffHighlightFilterTable = <table> {
 }
 unitEvents = <table> {
 }
 UNIT_POWER_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF_Plugins\oUF_EnergyManaRegen.lua:82
 UNIT_HEALTH_FREQUENT = <table> {
 }
 UNIT_MAXHEALTH = <table> {
 }
 __elements = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 Power = <unnamed> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 DebuffHighlight = <unnamed> {
 }
 EnergyManaRegen = <unnamed> {
 }
 UNIT_HAPPINESS = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 PLAYER_TOTEM_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\totems.lua:120
 Health = <unnamed> {
 }
 PvPIndicator = <unnamed> {
 }
 DebuffHighlightFilter = true
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\raidtargetindicator.lua:62
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 Totems = oUF_PlayerTotems {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 Portrait = PlayerPortrait {
 }
 SmoothBar = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF_Plugins\oUF_Smooth.lua:35
 UNIT_POWER_BAR_HIDE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 PORTRAITS_UPDATED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\portrait.lua:87
 RaidTargetIndicator = <unnamed> {
 }
 unit = "player"
 GROUP_ROSTER_UPDATE = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\leaderindicator.lua:59
 INCOMING_RESURRECT_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\resurrectindicator.lua:60
 PLAYER_UPDATE_RESTING = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\restingindicator.lua:58
 PLAYER_REGEN_ENABLED = <table> {
 }
 PARTY_LEADER_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\leaderindicator.lua:59
 Level = <unnamed> {
 }
 UNIT_AURA = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF_Plugins\oUF_DebuffHighlight.lua:34
 style = " "
 CURRENT_SPELL_CAST_CHANGED = <function> defined @Interface\AddOns\KkthnxUI\Modules\Unitframes\Core.lua:450
 DebuffHighlightAlpha = 0.450000
 PLAYER_REGEN_DISABLED = <table> {
 }
 UNIT_CONNECTION = <table> {
 }
 LeaderIndicator = <unnamed> {
 }
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF_Plugins\oUF_EnergyManaRegen.lua:82
 UNIT_FACTION = <table> {
 }
 0 = <userdata>
 HealthPrediction = <table> {
 }
 RestingIndicator = <unnamed> {
 }
 UNIT_FLAGS = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\elements\power.lua:249
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\KkthnxUI\Libraries\oUF\ouf.lua:190
 Overlay = <unnamed> {
 }
 CombatIndicator = <unnamed> {
 }
 Castbar = PlayerCastbar {
 }
 UNIT_MODEL_CHANGED

**Comment by Kkthnx** [comment]
Old
