### ISSUE TITLE
databars broken

### ISSUE THREAD

**Issue by PalletjeNL-Thura** [kkthnx-wow/KkthnxUI_Classic#10]
When enabling the databars the minimap turns to the default blizzard UI

Disabling them
![WoWScrnShot_091619_131008](https://user-images.githubusercontent.com/55385999/64953571-6d71ca00-d883-11e9-8b5c-1487ed100477.jpg)

Enabling them
![WoWScrnShot_091619_130957](https://user-images.githubusercontent.com/55385999/64953595-7a8eb900-d883-11e9-9c73-48ecab05f541.jpg)

**Comment by Baine** [comment]
issued a pull request which should fix this. please try again after it has been merged :)
