### ISSUE TITLE
[Suggestion] Indicator for energy ticks on druid/rogue player frames

### ISSUE THREAD

**Issue by lsa-89** [kkthnx-wow/KkthnxUI_Classic#17]
First off: Great work on the UI so far. It looks really sleek. Hats off for that.

I am missing some kind of indicator for when energy ticks occure, though. As a pvp player, this is a crucial feature and I would love to see something like that in this, otherwise, very impressive UI suite.

This is kind of the only thing holding me back right now to switch to your UI all the way.

Do your unit frames support healcomm btw? I have not tested this so far.

Greetings

**Comment by Kkthnx** [comment]
Healcomm, no.

I will look into the ticks 💃

**Comment by Kkthnx** [comment]
Added.
