### ISSUE TITLE
Gold tootlip refused to show up after updating to 1.10

### ISSUE THREAD

**Issue by freerunner** [Kkthnx-Wow/KkthnxUI_Classic#2]
Hi there,

been using KKthnxUI Classic from wowinterface (v1.09) for some weeks. Couple of days ago I've found out that curse had a v1.10 and did the upgrade.
After updating, hovering the mouse over the gold display stopped showing the tooltip with the details about income and expenses.

**Comment by freerunner** [comment]
May I ask if the project is still active?

**Comment by Kkthnx** [comment]
Old issue
