### ISSUE TITLE
[feature] Target nameplate

### ISSUE THREAD

**Issue by amonsat** [kkthnx-wow/KkthnxUI_Classic#25]
Be great if we can get option for nameplate on target, that ignoring distance for nameplates. It's very usefull for hunters. Also be cool option for nameplate just for target.

**Comment by Kkthnx** [comment]
I think Blizzard broke this recently and we can not control it.

**Comment by Baine** [comment]
https://www.wowhead.com/news=295078/blizzard-hotfixed-command-to-increase-nameplate-range-in-classic-wow

has been hotfixed by bliz. not possible from our site.
