### ISSUE TITLE
[feature] Add quest icon for items in invetory

### ISSUE THREAD

**Issue by amonsat** [kkthnx-wow/KkthnxUI_Classic#26]
Like on this image. (Exclamation point)

![image](https://user-images.githubusercontent.com/5467910/65706671-a08e3780-e093-11e9-9f14-5ad8b470b7ec.png)

**Comment by Kkthnx** [comment]
Good enough? 
![image](https://user-images.githubusercontent.com/40672673/65758286-d7416d80-e0e6-11e9-896a-cafb5f140446.png)

**Comment by amonsat** [comment]
magnificently

**Comment by Kkthnx** [comment]
Changed the color of the quest items to be more visible.
![image](https://user-images.githubusercontent.com/40672673/65759155-54211700-e0e8-11e9-96ed-1c2986fdb4c0.png)

**Comment by Kkthnx** [comment]
Added.
