### ISSUE TITLE
error you get when you click the install button on the gear on the chat box

### ISSUE THREAD

**Issue by evilintent** [Kkthnx-Wow/KkthnxUI_Classic#3]
Message: Interface/AddOns/KkthnxUI/Core/Install.lua:639: attempt to concatenate global 'RENOWN_LEVEL_UP_SKIP_BUTTON' (a nil value)
Time: Fri Dec 27 17:16:05 2024
Count: 1
Stack: Interface/AddOns/KkthnxUI/Core/Install.lua:639: attempt to concatenate global 'RENOWN_LEVEL_UP_SKIP_BUTTON' (a nil value)
[string "@Interface/AddOns/KkthnxUI/Core/Install.lua"]:639: in function `KKUI_INSTALLER'
[string "@Interface/AddOns/KkthnxUI/Modules/Chat/Elements/Copy.lua"]:44: in function `func'
[string "@Interface/AddOns/Blizzard_SharedXML/Classic/UIDropDownMenu.lua"]:975: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:148_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:148_OnClick"]:1>

Locals: welcomeLogo = Texture {
}
welcomeBoss = Texture {
}
ll = Frame {
}
lr = Frame {
}
ll = Frame {
}
lr = Frame {
}
goTutor = Button {
 KKUI_Border = <table> {
 }
 KKUI_Background = Texture {
 }
 text = FontString {
 }
}
goSkip = Button {
 KKUI_Border = <table> {
 }
 KKUI_Background = Texture {
 }
 text = FontString {
 }
}
(*temporary) = FontString {
}
(*temporary) = ""
(*temporary) = nil
(*temporary) = ""
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate global 'RENOWN_LEVEL_UP_SKIP_BUTTON' (a nil value)"
welcome = KKUI_Tutorial {
 KKUI_Border = <table> {
 }
 KKUI_Background = Texture {
 }
}
UIParent = UIParent {
 variablesLoaded = true
 Above = Spy_MainWindow {
 }
 firstTimeLoaded = 1
}
K = <table> {
 PetBattleFrameHider = Frame {
 }
 b = 0.410000
 g = 0.960000
 Race = "Undead"
 Mult = 1.006289
 PartyPetFlags = 4370
 LibBase64 = <table> {
 }
 Realm = "Nightslayer"
 Devs = <table> {
 }
 Changelog = <table> {
 }
 LeftButton = "  "
 ScreenWidth = 3440
 Profiles = KKUI_Profiles {
 }
 RaidPetFlags = 4372
 ClassColors = <table> {
 }
 UIFontSize = 12
 MyClassColor = ""
 QualityColors = <table> {
 }
 ScrollButton = "  "
 Sex = 2
 WowBuild = 57979
 Class = "ROGUE"
 ScreenHeight = 1440
 Colors = <table> {
 }
 UIFrameHider = Frame {
 }
 InfoColorTint = ""
 cargBags = Button {
 }
 TexCoords = <table> {
 }
 GUI = KKUI_GUI {
 }
 Name = "Evil"
 WowPatch = "1.15.5"
 LibActionButton = <table> {
 }
 SystemColor = ""
 GUID = "Player-6104-0374E2CE"
 RightButton = "  "
 WowRelease = "Dec  5 2024"
 Client = "enUS"
 ScanTooltip = KKUI_ScanTooltip {
 }
 Version = "10.6.0"
 LibDeflate = <table> {
 }
 AddOnVersion = <table> {
 }
 EasyMenu = KKUI_EasyMenu {
 }
 AddOns = <table> {
 }
 UIFont = "KkthnxUIFont"
 Faction = "Horde"
 LibSerialize = <table> {
 }
 GreyColor = ""
 TocVersion = 11505
 Defaults = <table> {
 }
 LibCustomGlow = <table> {
 }
 Modules = <table> {
 }
 Title = "KkthnxUI"
 InfoColor = ""
 LibChangeLog = <table> {
 }
 Level = 40
 LibEasyMenu = <table> {
 }
 oUF = <table> {
 }
 LibUnfit = <table> {
 }
 LibSharedMedia = <table> {
 }
 UIFontOutline = "KkthnxUIFontOutline"
 r = 1
 LibRangeCheck = <table> {
 }
 UIFontStyle = "OUTLINE"
 Resolution = "3440x1440"
 ClassList = <table> {
 }
 MediaFolder = "Interface\AddOns\KkthnxUI\Media\"
}
C = <table> {
 RaidUtilityBuffCheckList = <table> {
 }
 NameplateTrashUnits = <table> {
 }
 Media = <table> {
 }
 AutoOpenItems = <table> {
 }
 Minimap = <table> {
 }
 DebuffsTracking_PvE = <table> {
 }
 Party = <table> {
 }
 DeprecatedAuras = <table> {
 }
 Automation = <table> {
 }
 Skins = <table> {
 }
 Raid = <table> {
 }
 NameplateWhiteList = <table> {
 }
 AuraWatchList = <table> {
 }
 AuraWatch = <table> {
 }
 AutoQuestData = <table> {
 }
 WorldMap = <table> {
 }
 Inventory = <table> {
 }
 Misc = <table> {
 }
 General = <table> {
 }
 Auras = <table> {
 }
 CheckBadBuffs = <table> {
 }
 Boss = <table> {
 }
 Loot = <table> {
 }
 Chat = <table> {
 }
 themes = <table> {
 }
 SpellReminderBuffs = <table> {
 }
 defaultThemes = <table> {
 }
 DebuffsTracking_PvP = <table> {
 }
 NameplateShowPowerList = <table> {
 }
 Nameplate = <table> {
 }
 NameplateTargetNPCs = <table> {
 }
 MajorSpells = <table> {
 }
 WorldMapPlusData = <table> {

**Comment by Kkthnx** [comment]
Fixed https://github.com/Kkthnx-Wow/KkthnxUI_Classic/commit/9f42f0738b73f9ee06b5e870c66b9f6497f3c23c
