### ISSUE TITLE
[Suggestion] Pet Happiness Indicator

### ISSUE THREAD

**Issue by Baine** [kkthnx-wow/KkthnxUI_Classic#3]
Currently missing, but important for hunters in classic. please add if possible :)

**Comment by Kkthnx** [comment]
Temp added a fix for this with 
https://github.com/kkthnx-wow/KkthnxUI_Classic/commit/e64f0b02384ba626aba4131ee6287bf36f9484ee

**Comment by Kkthnx** [comment]
Going to leave this open though for the future to add a status indicator later.

**Comment by Kkthnx** [comment]
Opened a reminder for myself. https://github.com/kkthnx-wow/KkthnxUI_Classic/issues/18
