### ISSUE TITLE
error when you click movie or toggle frames... also umm the ui scale wont change at all 

### ISSUE THREAD

**Issue by evilintent** [Kkthnx-Wow/KkthnxUI_Classic#4]
Message: Interface/AddOns/KkthnxUI/Core/Movers.lua:217: attempt to call field 'AuraWatch' (a nil value)
Time: Fri Dec 27 17:21:21 2024
Count: 1
Stack: Interface/AddOns/KkthnxUI/Core/Movers.lua:217: attempt to call field 'AuraWatch' (a nil value)
[string "@Interface/AddOns/KkthnxUI/Core/Movers.lua"]:217: in function <Interface/AddOns/KkthnxUI/Core/Movers.lua:209>

Locals: self = Button {
 KKUI_Border = <table> {
 }
 KKUI_Background = Texture {
 }
 text = FontString {
 }
}
(*temporary) = nil
(*temporary) = "lock"
(*temporary) = "attempt to call field 'AuraWatch' (a nil value)"
MoverList = <table> {
 1 = KKUI_Mover {
 }
 2 = KKUI_Mover {
 }
 3 = KKUI_Mover {
 }
 4 = KKUI_Mover {
 }
 5 = KKUI_Mover {
 }
 6 = KKUI_Mover {
 }
 7 = KKUI_Mover {
 }
 8 = KKUI_Mover {
 }
 9 = KKUI_Mover {
 }
 10 = KKUI_Mover {
 }
 11 = KKUI_Mover {
 }
 12 = KKUI_Mover {
 }
 13 = KKUI_Mover {
 }
 14 = KKUI_Mover {
 }
 15 = KKUI_Mover {
 }
 16 = KKUI_Mover {
 }
 17 = KKUI_Mover {
 }
 18 = KKUI_Mover {
 }
 19 = KKUI_Mover {
 }
 20 = KKUI_Mover {
 }
 21 = KKUI_Mover {
 }
 22 = KKUI_Mover {
 }
 23 = KKUI_Mover {
 }
 24 = KKUI_Mover {
 }
 25 = KKUI_Mover {
 }
 26 = KKUI_Mover {
 }
 27 = KKUI_Mover {
 }
 28 = KKUI_Mover {
 }
 29 = KKUI_Mover {
 }
 30 = KKUI_Mover {
 }
 31 = KKUI_Mover {
 }
 32 = KKUI_Mover {
 }
 33 = KKUI_Mover {
 }
 34 = KKUI_Mover {
 }
 35 = KKUI_Mover {
 }
 36 = KKUI_Mover {
 }
 37 = KKUI_Mover {
 }
 38 = KKUI_Mover {
 }
}
f = Frame {
 KKUI_Background = Texture {
 }
 __trimText = FontString {
 }
 KKUI_Border = <table> {
 }
 text = FontString {
 }
 __y = EditBox {
 }
 __x = EditBox {
 }
}

**Comment by Kkthnx** [comment]
Such issues are going to be present until I can work through modules.

**Comment by Kkthnx** [comment]
Fixed https://github.com/Kkthnx-Wow/KkthnxUI_Classic/commit/bec1fe177b181ddd54d135f32e8cd4ad48c11cb5
