### ISSUE TITLE
 while on fp it  just popped up

### ISSUE THREAD

**Issue by evilintent** [Kkthnx-Wow/KkthnxUI_Classic#5]
Message: Interface/AddOns/BigDebuffs/BigDebuffs.lua:583: attempt to index field 'unitFrame' (a nil value)
Time: Fri Dec 27 18:04:05 2024
Count: 2
Stack: Interface/AddOns/BigDebuffs/BigDebuffs.lua:583: attempt to index field 'unitFrame' (a nil value)
[string "@Interface/AddOns/BigDebuffs/BigDebuffs.lua"]:583: in function `func'
[string "@Interface/AddOns/BigDebuffs/BigDebuffs.lua"]:2354: in function `?'
[string "@Interface/AddOns/AutoLayer_Vanilla/Lib/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...Lib/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AutoLayer_Vanilla/Lib/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Lib/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AutoLayer_Vanilla/Lib/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/AutoLayer_Vanilla/Lib/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...Layer_Vanilla/Lib/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: frame = NamePlate2 {
 driverFrame = NamePlateDriverFrame {
 }
 namePlateUnitToken = "nameplate2"
 UnitFrame = Button {
 }
 template = "NamePlateUnitFrameTemplate"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'unitFrame' (a nil value)"

**Comment by Kkthnx** [comment]
This isnt because of my addon.
