### ISSUE TITLE
Addon conflict with DagAssist

### ISSUE THREAD

**Issue by AussieEevee** [kkthnx-wow/KkthnxUI_Classic#56]
When the addon DagAssist is installed, the minimap recycle bin does nothing. It doesn't generate an error. It just doesn't respond to clicks.

I added

`["DA_Minimap"] = true,`

to the blacklist under Modules/maps/MinimapButtons.lua as a temporary work around.

**Comment by Kkthnx** [comment]
Noted, Thank you very much @AussieEevee
