### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by alpineboi20** [kkthnx-wow/KkthnxUI_Classic#57]
Hello
Firstly please would it possible to add adjustable x y position class icons for nameplates. 
I have severe colour-blindness, so it would be a great addition if possible. I currently use threat plates at the moment as it has this feature & disable the nameplates' module in KkthanksUI, but want to keep add-ons to minimum & like the idea of having everything I need in one place.

I made some custom icons a while ago whilst attempting to do it myself, but didn't have any luck getting it to work. If you would like to use them you can get them here https://filebin.net/twaramxg1r6z2hb7

Secondly if possible could you add an option to disable/hide Buffs/Debuffs in the top right corner of the screen? I can disable blizzards Buffs/Debuffs using a third party add-on but not KkthanksUI.

Thank You

**Comment by Kkthnx** [comment]
Something like this? Ofc its not done but its a mock up.

![image](https://user-images.githubusercontent.com/40672673/66584348-f6161a00-eb52-11e9-899f-5f5adbb15022.png)

**Comment by alpineboi20** [comment]
Yes exactly like that would be amazing :)

**Comment by Kkthnx** [comment]
![image](https://user-images.githubusercontent.com/40672673/66584790-c0bdfc00-eb53-11e9-87cb-f39b932e653d.png)
![image](https://user-images.githubusercontent.com/40672673/66584802-c74c7380-eb53-11e9-8a00-a5cb1e83b105.png)

**Comment by Kkthnx** [comment]
Ofc when they cast the cast bar should overlap it so it will be on top.

**Comment by alpineboi20** [comment]
I have mine on the left like in the mock-up, but on top would be fine. However, wouldn't auras have to be slightly higher then ?

**Comment by Kkthnx** [comment]
Right now its hard coded left though might add more options later for it.

**Comment by alpineboi20** [comment]
Whatever you can do will be much appreciated. Thank you very much :)

**Comment by Kkthnx** [comment]
Your other request will be added later.

**Comment by alpineboi20** [comment]
You're the best, thanks again :)
