### ISSUE TITLE
Latency fps bar wrong position

### ISSUE THREAD

**Issue by PalletjeNL-Thura** [kkthnx-wow/KkthnxUI_Classic#8]
The latency or fps bar is on the wrong position of the screen, this should be on the minimap, but is on the left top corner of the screen

![WoWScrnShot_091619_115456](https://user-images.githubusercontent.com/55385999/64949225-00593700-d879-11e9-9f66-5f5bea3ec5b5.jpg)

**Comment by Kkthnx** [comment]
This is intended to free up space on the minimap.
