### ISSUE TITLE
UI size too small on a 2k resolution

### ISSUE THREAD

**Issue by PalletjeNL-Thura** [kkthnx-wow/KkthnxUI_Classic#9]
I have a 2k resolution (2560x1440) and the UI is too small with autoscaling.

Size at its largest
![WoWScrnShot_091619_115820](https://user-images.githubusercontent.com/55385999/64949404-634ace00-d879-11e9-8ca4-334df8cb2bfa.jpg)

Size at its smalles (only some aspects seem to change size)
![WoWScrnShot_091619_115830](https://user-images.githubusercontent.com/55385999/64949447-7f4e6f80-d879-11e9-920c-917d7206751c.jpg)

the questlog is not easy to read without glasses
![WoWScrnShot_091619_120111](https://user-images.githubusercontent.com/55385999/64949561-bd4b9380-d879-11e9-9af6-f6216c979374.jpg)

In comparison the combat text is quite big
![WoWScrnShot_091619_120529](https://user-images.githubusercontent.com/55385999/64949833-5d092180-d87a-11e9-818d-f05a7a7a2018.jpg)

The ui size without your addon is much bigger
![WoWScrnShot_091619_120707](https://user-images.githubusercontent.com/55385999/64949918-8c1f9300-d87a-11e9-924b-ee338627e88a.jpg)

and seem to be growing in size when the slider is moved to the right instead of getting smaller
![WoWScrnShot_091619_120823](https://user-images.githubusercontent.com/55385999/64950041-ce48d480-d87a-11e9-93ac-268d3815cd69.jpg)

It works fine when autoscaling is off and a manual number is put in (for me 0.65 is ok

**Comment by Kkthnx** [comment]
KkthnxUI > General > Uncheck AutoScale and then type your scale you want in UIScale editbox.
